# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConjugationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('conjugation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='verbes.Conjugation')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoodTense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes.Mood')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(choices=[('s', 'singulier'), ('p', 'pluriel')], max_length=1)),
                ('index', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('number', 'index')]),
        ),
        migrations.AddField(
            model_name='moodtense',
            name='tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes.Tense'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='mood_tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes.MoodTense'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes.Person'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes.Verb'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='conjugation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes.Conjugation'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='conjugationvalue',
            unique_together=set([('conjugation', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='conjugation',
            unique_together=set([('verb', 'mood_tense', 'person')]),
        ),
    ]
